
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsgxgahebefyjpxrrbyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZ3hnYWhlYmVmeWpweHJyYnl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTMxNzUsImV4cCI6MjA1MjUyOTE3NX0.d1e0YrDMiLEXSPG7cSFQ8xwdX4P4KRzOJTTl96lthUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to create a URL to our edge function
export const getEdgeFunctionUrl = (functionName: string): string => {
  // For local development
  if (window.location.hostname === 'localhost') {
    return `${SUPABASE_URL}/functions/v1/${functionName}`;
  }
  
  // For production
  return `${window.location.origin}/${functionName}`;
};
